### ISSUE TITLE
t-critical value in confidence interval

### ISSUE THREAD

**Issue by elashoffb** [AntoineSoetewey/statistics-201#5]
For the alternative hypothesis ">", the t-critical value in the formula for the confidence interval is computed using the area= alpha/2, even though it is a one-sided test.  Is there a reason you did that?

**Comment by AntoineSoetewey** [comment]
Dear Barbara,

Thanks for your question.

In this app, only **bilateral** (two-sided) confidence intervals are computed. For hypothesis tests, bilateral **and** unilateral tests are computed.

So if you want to compute a unilateral confidence interval, you should indeed use alpha instead of alpha/2.

The reason for that is that the code of the app is already quite complex, so I decided to not do unilateral (one-sided) confidence intervals (and also because they are less common). But if you find the time to improve the app, feel free to submit a pull request.

I have added a note in the app to make this clearer, see: https://github.com/AntoineSoetewey/statistics-201/commit/36da729721020b8a94ae55add573800edbb19fa1.

Regards,
Antoine

**Comment by elashoffb** [comment]
Dear Antoine,
Thank you for that explanation!  I figured you must have had a reason.
Best,
Barbara

**Comment by AntoineSoetewey** [comment]
Dear @elashoffb,

After a very long time, I finally took the time to fix this (see https://github.com/AntoineSoetewey/statistics-201/commit/b747f346b97bf8b3635b40d024fd8fbc9182a8de).

Feel free to let me know if you have any questions or remarks!

Regards,
Antoine
